const TechnicalLists = [
  {
    id: 1,
    name: "autocad-civil",
    imgSrc: "/assets/Workshops/Autocad Civil.webp",
    heading: "AutoCAD (Civil)",
    headingPara:
      "AutoCAD is a computer-aided design (CAD) software application used for 2D and 3D design and drafting. In the civil engineering domain, AutoCAD is used for designing and drafting blueprints of infrastructure projects such as buildings, bridges, and roads.",
    certiPara:
      "On successful completion of this 1-day Workshop, you will earn yourself a Certification in AutoCAD (Civil).",
    rules: [
      "1. Introduction to AutoCAD and its interface.",
      "2. Understanding basic drawing commands like line, circle, rectangle, etc.",
      "3. Drawing and editing 2D geometry in AutoCAD.",
      "4. Working with layers and properties.",
      "5. Creating and editing blocks.",
      "6. Dimensioning and adding annotations.",
      "7. Introduction to 3D modelling.",
      "8. Creating 3D models using extrude, revolve and sweep commands.",
      "9. Introduction to civil engineering drawings.",
      "10. Drawing civil engineering plans like site plan, floor plan, elevation plan.",
      "11. Generating accurate measurements and quantities.",
      "12. Plotting and printing drawings.",
    ],
    paymentLink: "https://tally.so/r/3EKRjr",
    redirectLink: "/events/technical/autocad-civil",
  },
  {
    id: 2,
    name: "solidworks",
    imgSrc: "/assets/Workshops/Mech Solid Works.webp",
    heading: "SolidWorks",
    headingPara:
      "SolidWorks is a 3D CAD software used for designing mechanical parts and assemblies. It is widely used in the manufacturing industry for product design and development.",
    certiPara:
      "On successful completion of this 2-day Workshop, you will earn yourself a Certification in SolidWorks.",
    rules: [
      "1. Introduction to SolidWorks and its interface.",
      "2. Understanding sketches and basic sketching tools.",
      "3. Creating and editing 2D sketches.",
      "4. Creating 3D models using extrude, revolve, sweep, and loft commands.",
      "5. Working with assemblies and mates.",
      "6. Creating exploded views.",
      "7. Creating animations and basic motion studies.",
      "8. Introduction to sheet metal design.",
      "9. Creating sheet metal parts and assemblies.",
      "10. Creating drawings with dimensions and annotations.",
      "11. Generating accurate measurements and quantities.",
      "12. Plotting and printing drawings.",
      "13. Advanced features like surfaces and advanced assemblies (time permitting).",
    ],
    paymentLink: "https://tally.so/r/3EKRjr",
    redirectLink: "/events/technical/solidworks",
  },
  {
    id: 3,
    name: "cybersec",
    imgSrc: "/assets/Workshops/Cyber Security.webp",
    heading: "Cyber Security",
    headingPara:
      "Cyber security is the practice of protecting computers, servers, mobile devices, electronic systems, networks, and data from digital attacks, theft, and damage. This workshop will provide an introduction to the fundamentals of cyber security.",
    certiPara:
      "On successful completion of this 3-hour Workshop, you will earn yourself a Certification in Cyber Security.",
    rules: [
      "1. Introduction to Cyber Security and the different types of hacking.",
      "2. Understanding common misconceptions about hacking and ethical hacking.",
      "3. Essential terminologies and elements of Information Security.",
      "4. Steps involved in hacking and how to get started.",
      "5. How to improve your skills and find job/internship opportunities in Cyber Security.",
      "6. The importance of community in Cyber Security and introduction to bug bounty.",
      "7. Cyber hygiene practices to avoid being hacked.",
      "8. Hands-on lab sessions on Basic Recon, Network Scanning, Enumeration, Fuzzing for directories, Sensitive file disclosure, and Privilege Escalation.",
      "9. Common web vulnerabilities and basic OSINT techniques.",
      "10. Identification of IDOR Vulnerability and how to mitigate them.",
      "11. Analyzing findings and generating final reports.",
      "12. Q&A session with industry experts.",
    ],
    paymentLink: "https://tally.so/r/3EKRjr",
    redirectLink: "/events/technical/cybersec",
  },
  {
    id: 4,
    name: "iot",
    imgSrc: "/assets/Workshops/Iot.webp",
    heading: "IoT",
    heading: "Internet of Things (IoT)",
    headingPara:
      "The Internet of Things (IoT) is a system of interrelated devices, mechanical and digital machines, objects, animals or people that are provided with unique identifiers (UIDs) and the ability to transfer data over a network without requiring human-to-human or human-to-computer interaction. This workshop will introduce you to the basics of IoT and how it can be used to build innovative projects.",
    certiPara:
      "On successful completion of this 2-day Workshop, you will earn yourself a Certification in IoT.",
    rules: [
      "1. Introduction to IoT and its applications.",
      "2. Understanding the basics of electronics and circuits.",
      "3. Introduction to microcontrollers and their programming.",
      "4. Setting up an IoT environment with sensors and actuators.",
      "5. IoT communication protocols and standards.",
      "6. Data collection and analysis using IoT devices.",
      "7. Introduction to cloud computing and IoT platforms.",
      "8. Integrating IoT devices with web and mobile applications.",
      "9. Building an IoT project from scratch.",
      "10. Testing and deploying an IoT project.",
      "11. Understanding the security and privacy aspects of IoT.",
      "12. Future trends and possibilities in IoT.",
    ],
    paymentLink: "https://tally.so/r/3EKRjr",
    redirectLink: "/events/technical/iot",
  },
];

export default TechnicalLists;
