const CulturalLists = [
    {   
        name: "desafio",
        id: 1,
        imgSrc: "/assets/cultural/pic.png",
        heading: "Desafio - Dance Competiton",
        para: "Dancers don't need wings to fly. Waiting for such an Opportunity? Then here is the chance, KARMA '22 brings you the 'Desafio' dance competition !! Grab your chance now, dance from your heart and let your passion shine through !",
        rule1: "1. No participants in group: min 4 and max 12 students.",
        rule2: "2. Time limit : 7+1 minutes.",
        rule3: "3. Theme : Folk dance/ Patriotic/ Religious/ Hindi.",
        rule4: "4. Style : Any style of dance (depend on participant).",
        rule5: "5. Participants are required to bring their own music CDs and props.",
        rule6: "6. Confirm the song and provide the CD to the concerned faculty co-coordinator of the event.",
        rule7: "7. There should be only one entry in front of each college.",
        rule8: "8. Judges can stop the dance in between if they feel it is irrelevant.",
        rule9: "",
        rule10: "",
        paymentLink: "https://rzp.io/l/Desafio-Dance",
        redirectLink: "/events/cultural/desafio",
    },
    {
        id: 2,
        name: "pencildrawing",
        para: "Are you ready to beat you boredom?and fly high in the world of imagination,then the opportunity is here,𝐊𝐀𝐑𝐌𝐀'𝟐𝟐 brings you '𝐋𝐀𝐏𝐈𝐙' 𝐏𝐞𝐧𝐜𝐢𝐥 𝐃𝐫𝐚𝐰𝐢𝐧𝐠 𝐂𝐨𝐦𝐩𝐞𝐭𝐢𝐭𝐢𝐨𝐧 ,Let your minds step into world of imagination...let's be engaged for while lost in thoughts... Let your white papers be kissed by pencil..",
        imgSrc: "/assets/cultural/pencildrawing.png",
        heading: "LAPIZ - Pencil Drawing Competition",
        rule1: "1. Entries must follow the competition theme.",
        rule2: "2. It is an open event, on the spot registrations are allowed.",
        rule3: "3. Only one entry per person, no group entries allowed.",
        rule4: "4. Participants are required to bring their own pencils.",
        rule5: "5. Decision of the judges will be final and cannot be challenged.",
        rule6: "6. There will be a time limit for completion.",
        rule7: "7. A finished art should not contain any other materials.",
        rule8: "8. Each participants will receive a registration number after the registration, it should be written on the top left corner of the final art.",
        rule9: "",
        paymentLink: "https://rzp.io/l/Pencil-Drawing",
        redirectLink: "/events/cultural/pencildrawing"
    },
    {
        id: 3,
        name: "fashionshow",
        para: "Are you a fashionista or a dressy, kicky, sassy person? If yes, then what are you waiting for? KARMA '22 is here with 'VOGUE FIESTA' Fashion show' ! Style is a way to say who you are without having to speak. Create your own visual style. Let it be unique for yourself and yet identifiable for others ! All fashion lovers do participate and make sure you have registered.",
        imgSrc: "/assets/cultural/fashionshow.png",
        heading: "Vogue Fiesta - Fashion Show",
        rule1: "1. Cross college teams will not be awarded any Karma points if they win.",
        rule2: "2. A minimum of 6 and a maximum of 30 models per team are allowed.",
        rule3: "3. One participant cannot be a part of two participating teams.",
        rule4: "4. Time limit per team: 10 minutes empty to empty.",
        rule5: "5. An additional 1 minute, if required, will be provided for narration only.Exceeding the time limit will lead to team disqualification.",
        rule6: "6. Participating teams should upload a video of their past performance to a drive, and send the link along with the following information to karmakmct2022@gmail.com by 15th May 2022.",
        rule7: "7. College Name (and Team Name, if any) -Name and Contact Info of any 3 team members.",
        rule8: "8. List of Team members Shortlisted teams will be informed by mail.",
        rule9: "9. Background music should be sent by email to karmakmct2022@gmail.com as a new email named VF-BGM-[College Name]. Both the subject of the mail and the Background music should be named in this format.",
        rule10: "10. The deadline for the same shall be informed after confirmation of participation. Presenting banners, posters or other materials directly displaying the theme is prohibited.",
        paymentLink: "https://rzp.io/l/Fashion-Show",
        redirectLink: "/events/cultural/fashionshow"
    },
    {
        id: 4,
        name: "lightmusic",
        para: "Music is the universal language of mankind. Where words fail, music speaks. 𝐊𝐀𝐑𝐌𝐀'𝟐𝟐 is here with ' 𝐋𝐢𝐠𝐡𝐭 𝐌𝐮𝐬𝐢𝐜 𝐂𝐨𝐦𝐩𝐞𝐭𝐢𝐭𝐢𝐨𝐧 '. Do participate and never miss a chance to show up your passion. Let your words speak through music !",
        imgSrc: "/assets/cultural/lightmusic.png",
        heading: "Light Music",
        rule1: "1. Participant should choose a meaningful song of about 5 minutes duration.",
        rule2: "2. The song should not be devotional, choral or from Films.",
        rule3: "3. Use of single instrument other than organ by the participant is permitted.",
        rule4: "4. Composition and overall impression",
        rule5: "",
        rule6: "",
        rule7: "",
        rule8: "",
        rule9: "",
        paymentLink: "https://pages.razorpay.com/Karma22LightMusic",
        redirectLink: "/events/cultural/lightmusic"
    },
]

export default CulturalLists;