const GamesLists = [
  {
    id: 1,
    name: "carroms",
    imgSrc: "/assets/Games/carroms.webp",
    heading: "Carroms",
    para: "Join us for an exciting game of Carroms at KARMA'23 and compete with your peers for the ultimate prize. Show off your skills and win prizes worth 5k!",
    rules:["1. Competition will be  conducted in the supervision of judges and the decision of them will be final. "],
    regFee: " 50/-",
    paymentLink: "https://api.whatsapp.com/send/?phone=%2B918139026688&text=Hi,%20Iam+interested+in+carroms+competition!!",
    redirectLink: "/events/games/carroms",
  },
  {
    id: 2,
    name: "treasure-hunt",
    imgSrc: "/assets/Games/treasure.webp",
    heading: "Treasure Hunt",
    para: "Get ready for an adventure like no other at KARMA'23 with our Treasure Hunt competition. Put your problem-solving skills to the test and win prizes worth 5k while having a blast!",
    rules: ["1. Competition will be  conducted in the supervision of judges and the decision of them will be final. ",
    "2. Maximum four members.",
    "3. First team to solve all the clues win.",
    "4. Elimination based game.",
    "5. Malpractices are forbidden!"],
    regFee: " 50/-",
    paymentLink: "https://api.whatsapp.com/send/?phone=%2B919895671179&text=Hi,%20Iam+interested+in+tressure+hunt+competition!!",
    redirectLink: "/events/games/treasure-hunt",
  },
  {
    id: 3,
    name: "chess",
    imgSrc: "/assets/Games/chess.png",
    heading: "Checkmate",
    para: "Amidst the stillness of the board,Where black and white converge,A game of kings and queens is played,As minds begin to merge, KARMA'23 is here with chess competition with prize worth 5k!",
    rules: ["1. Competition will be  conducted in the supervision of judges and the decision of them will be final.",
            "2. The competition will be conducted at the venue.",
            "3. Elimination based competition!",
            "4. Individual competition."],
    regFee: " 50/-",
    paymentLink: "https://api.whatsapp.com/send/?phone=%2B919846265681&text=Hi,%20Iam+interested+in+chess+competition!!",
    redirectLink: "/events/games/chess",
  },
];

export default GamesLists;
