const GamesLists = [
  {
    id: 1,
    name: "pubg",
    imgSrc: "/assets/Games/pubg.svg",
    heading: "PUBG",
    para: "KARMA'22 Is here with the PUBG- Chosen game by over 1 billion players worldwide Competition for the game enthusiasts. Play your favourite game and win over prizes worth 15k",
    rules: [
      "1. The competition will be supervised by the match controller and the decision of them will be final.",
      "2. Mobile players only.",
      "3. Solo Room Match and the map will be announced at the start if the game.",
      "4. The competition will be conducted from the venue.",
      "5. Hackers and emulator's will be disqualified",
      "6. Faking or manipulating match media is forbidden.",
      "7. Teams are responsible for their own technical issues (hardware/internet).",
    ],
    regFee: " 50/-",
    paymentLink: "https://rzp.io/l/Karma-PUBG",
    redirectLink: "/events/games/pubg",
  },
  {
    id: 2,
    name: "ludo",
    imgSrc: "/assets/Games/LUDO.png",
    heading: "LUDO",
    para: "KARMA'22 is here with the amazing Ludo Competition for all the Ludo Kings and Queens. Show off all your skills you acquired on quarantine with this Ludo Game and win prizes worth 30K",
    rules: [
      "1. Competition will be done in the supervision of judges.",
      "2. The competition will be conducted at the venue. ",
      "3. No malpractices are allowed. ",
    ],
    regFee: " 30/-",
    paymentLink: "https://rzp.io/l/Karma-Ludo",
    redirectLink: "/events/games/ludo",
  },
  {
    id: 3,
    name: "pes",
    imgSrc: "/assets/Games/PES.png",
    heading: "PES",
    para: "KARMA'22 Presents PES Tournament  for all the PES players. Display your skills and win prizes over 15 K.",
    rules: [
      "1. Competition will be  conducted in the supervision of judges and the decision of them will be final. ",
      "2. No Team Strength",
      "3. 8 Minutes Gameplay",
      "4. Single Match (No Home and Away)",
      "5. Faking or manipulating match media are forbidden.",
    ],
    regFee: " 100/-",
    paymentLink: "https://rzp.io/l/Karma-PES",
    redirectLink: "/events/games/pes",
  },
];

export default GamesLists;
